### ISSUE TITLE
Light Mode Support

### ISSUE THREAD

**Issue by deboer-tim** [podman-desktop/podman-desktop#4914]
### Epic domain

We have had requests for light mode for some time for obvious reasons: astigmatism, system default, or just users who prefer it better. Opening this epic to track the overall work.

### Additional context

Initial request: #576 (maybe can be the 'final' issue we resolve to expose the mode).

Technical implementation:

- [x] #4887 - initial PR to add hidden light mode setting
- [x] #4907 - discussion on mapping colors
- [ ] #4912 - draft to try things out
- [ ] #5116 - remove hardcoded references to dark icons/add light support
- [x] #5878 - Create abstract color references to better enable theming

Sprint 256:
- [x] #6929 - Define colors in palette
- [x] #6889 - Main nav/form page components
- [x] #6890 - Images and volumes tables
- [x] #6924

Sprint 257:
- [x] #7168
- [x] #6925
- [x] #6927
- [x] #7215
- [x] #7183
- [x] #7184
- [x] #7213
- [x] #7362 

Sprint 258:
- [x] #6926
- [x] #7185
- [x] #7214
- [x] #7348 
- [x] #7236
- [x] #7212
- [x] #7346
- [x] #7345
- [x] #7574
- [x] #7575
- [x] #7592
- [x] #7579
- [x] #7718
- [x] #7708
- [x] #7727 

Sprint 259:
- [x] #7547
- [x] #7548
- [x] #7544
- [x] #7608
- [x] #7728 
- [x] #7724
- [x] #6199
- [x] #7936

Sprint 260:
- [x] #7343
- [x] #7344
- [x] #7998
- [x] #7546 
- [x] #7545 
- [x] #8001
- [x] #8077
- [x] #8111
- [x] #8140
- [x] #8202
- [x] #8217
- [x] #8234
- [x] #8201
- [x] #8203

Sprint 261
- [x] #8380
- [x] #8397
- [x] #8393
- [x] #8447
- [x] #8440

Sprint 262
- [x] #8734
- [x] #8411
- [x] #8477
- [x] #8587

**Comment by benoitf** [comment]
@deboer-tim : maybe we change #576 to be the epic as most of the people are following this issue ?

**Comment by deboer-tim** [comment]
I almost did that, then thought most of those users just want to know when it is 'planned' and 'available' and don't care as much about the overall status or steps to get there. If you think it's better we can move to #576 and close this one.

**Comment by benoitf** [comment]
no I'm fine, you're right

**Comment by deboer-tim** [comment]
We have merged over 60 PRs and closed 60 issues. Light mode is released and announced. There are still a couple bugs to address and we may find more, but we no longer need to track progress via an epic so I am going to close this.

Thank you everyone for delivering on this highly requested community feature!
