### ISSUE TITLE
create new GitHub templates repository to bootstrap extensions

### ISSUE THREAD

**Issue by benoitf** [podman-desktop/podman-desktop#6301]
### Is your enhancement related to a problem? Please describe

With GitHub you can create template repositories, we should have at least 2 templates being available and documented

- [x] one with a basic "backend only" example https://github.com/containers/podman-desktop/issues/8537
- [x] one with a webview https://github.com/containers/podman-desktop/issues/8536
- [x] one with full (EDIT: added by charlie) https://github.com/containers/podman-desktop/issues/7634

### Describe the solution you'd like

Create the two repositories that will serve as templates, people only have to click on the link to start their new extension

**Comment by axel7083** [comment]
Where does the repository should be hosted ? under which organization ?

**Comment by benoitf** [comment]
@axel7083 it could be in containers org

**Comment by cdrage** [comment]
Webview template has been created and all updates (readme, code annotations, etc.) pushed: https://github.com/containers/podman-desktop-extension-template-webview

**Comment by cdrage** [comment]
CLosing as all 3 templates have been added / merged.
